### ISSUE TITLE
Github API: use the Authorization HTTP header.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/githubapi#21]
this was originally reported in https://github.com/backdrop-ops/backdropcms.org/issues/636 by @jenlampton  ... I've transferred the issue this queue.

-----

We got this email today from GitHub:

`[GitHub API] Deprecation notice for authentication via URL query parameters`

---

Hello there!

On February 3rd, 2020 at 22:19 (UTC) your application (BackdropCMS.org) used an access token (with the User-Agent Backdrop CMS GitHub API module) as part of a query parameter to access an endpoint through the GitHub API.

https://api.github.com/repositories/45898954/readme

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team

**Comment by serundeputy** [comment]
@jenlampton @quicksketch I've filed a PR to use the auth headers instead of query params.
PR: https://github.com/backdrop-contrib/githubapi/pull/22

I tested via `drush scr tst.php` where `tst.php` is:

```php
$settings = [
  ':owner' => 'backdrop-contrib',
  ':name' => 'githubapi'
];
$gh = githubapi_get_class($settings);
$release = $gh->getRequest(
  "repos/:owner/:name/pulls",
  $settings
);

print_r($release);
return;
```

It returned data from github; not sure if that is a sufficient test or not.

* Next steps are to approve/remediate this PR
* Merge PR
* New release of `githubapi` module
* Update `githubapi` module on b.org

thanks,
~Geoff

**Comment by quicksketch** [comment]
I reviewed the changes and the premise looks good. Other feedback: https://github.com/backdrop-contrib/githubapi/pull/22#pullrequestreview-359374934

**Comment by serundeputy** [comment]
thanks @quicksketch 
I've addressed the review remediation w/ updated PR: https://github.com/backdrop-contrib/githubapi/pull/22

**Comment by quicksketch** [comment]
Thanks @serundeputy, merged https://github.com/backdrop-contrib/githubapi/pull/22. I'll make a new release shortly.
