### ISSUE TITLE
Fix the capitalization of "GithubAPI" class?

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/githubapi#5]
I'm not sure about this one, but the the word `GitHub` is always spelled with a capital **`H`**. https://github.com/about

It seems that the class `GithubAPI` be capitalized as `GitHubAPI` instead then?

This is mostly a matter of preference, it won't affect the actual API itself because PHP is case-insensitive when it comes to class names.

**Comment by klonos** [comment]
:+1: from me on using capital `H` in `GitHub` ...but then again I'm sure you'd expect that from me:

https://github.com/backdrop/backdrop-issues/issues/158#issuecomment-68500999

I think I might have created a monster :wink:

**Comment by Gormartsen** [comment]
Fixed. I hope I did not miss it anywhere. See: https://github.com/backdrop-contrib/githubapi/commit/56535e4102d6ecf498795aa29cc20fee812fa4ba
